class CoralScrollCore{constructor(e){this.coralScrollElement=e,this.sliderElement=e.querySelector(".coral-scroll__slider"),this.grabOverlayElement=e.querySelector(".coral-scroll__grab-overlay"),this.sliderConfig=this.createSliderConfig(),this.slideScrollLeft=this.sliderElement.scrollLeft,this.showOverlay=!1,this.isDown=!1,this.startX,this.initializeSlider(),this.oberserverConfig={attributes:!1,childList:!0,subtree:!1},new MutationObserver(this.callback).observe(this.coralScrollElement,
this.oberserverConfig)}#createDotElement=e=>`<button type="button" class="dot" data-index="${e}" aria-label="Select slide ${e}" name="Select slide ${e}"></button>`;sendEventScrolledToNewSlide=e=>{e=new CustomEvent("scrolled-to-slide",{detail:{activeSlide:e}});document.dispatchEvent(e)};debounce=(t,s=50)=>{let i;return(...e)=>{clearTimeout(i),i=setTimeout(()=>{t.apply(this,e)},s)}};createSliderConfig=()=>{var e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"
)?this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")[0]:null;return{devMode:!!this.coralScrollElement.dataset.devMode&&"true"===this.coralScrollElement.dataset.devMode,grabVelocity:this.coralScrollElement.dataset.grabVelocity||100,enableThumbs:!!this.coralScrollElement.dataset.thumbs,infinite:"true"===this.coralScrollElement.dataset.infiniteScroll,snapAlignStyle:e?getComputedStyle(e)["scroll-snap-align"]:null,startPositionId:this.coralScrollElement.dataset.startPositionId}};
getCurrentSliderStates=()=>{if(!this.sliderElement)return null;var t=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),t=t?[...t]:null,s=getComputedStyle(this.sliderElement).paddingLeft.replace("px",""),i=getComputedStyle(this.sliderElement).gap;const l=i?.split(" ")?i?.split(" ")[0].replace("px",""):i?.replace("px","");var r=this.sliderElement.getBoundingClientRect().width;const n=t.length,o=Number(this.sliderElement.getBoundingClientRect().left)+Number(s);i=t.map(e=>{
var t=e.getBoundingClientRect().x,s=e.getBoundingClientRect().width;this.sliderElement.getBoundingClientRect().width,getComputedStyle(this.sliderElement).paddingLeft.replace("px",""),getComputedStyle(this.sliderElement).paddingRight.replace("px","");switch(this.sliderConfig.snapAlignStyle){case"start":return Number(t)-Number(o);case"center":return Number(t)-Number(o)+Number(s/2);default:return t}}),s=t.map(e=>{var t=e.getBoundingClientRect().x,e=e.getBoundingClientRect().width;return Number(t
)+Number(e)}),t=t.map((e,t)=>{e=e.getBoundingClientRect().width;return t===n?Number(e):Number(e)+Number(l.match(/^[0-9]+$/)?l:0)});if(0<i.length){const h=i?.reduce((e,t)=>Math.abs(+t)<Math.abs(+e)?t:e);var d=i?.findIndex(e=>e===h),a=getComputedStyle(this.sliderElement).paddingRight.replace("px",""),c=Math.ceil(s[n-1]),s=d===Number(n)-2;let e=null;switch(this.sliderConfig.snapAlignStyle){case"start":e=Number(c)+Number(a)<=Number(r)+10&&Number(c)+Number(a)>=Number(r)-10;break;case"center":
e=c-a==r/2;break;default:e=c===r}t={allSlideWidths:t,currentSlidePositions:i,activeSlide:d,isSlideTheSecondLastSlide:s,isSlideTheLastSlide:e};return this.sliderConfig.devMode&&console.log(t),t}return 0};setActiveIndicator=i=>{var e=this.coralScrollElement.querySelector(".coral-scroll__indicator");if(e){e=e.querySelectorAll(".dot");const l=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")],r=l[i],n=r?.classList.contains("js-clone");e.forEach(e=>{if(e.classList.remove("js-active"),
n){const s=r.dataset.cloneId;var t=l.findIndex(e=>e.dataset.slideId==s);Number(e.dataset.index)===Number(t)&&e.classList.add("js-active")}else Number(e.dataset.index)===Number(i)&&e.classList.add("js-active")})}};setActiveThumb=n=>{var e=this.sliderElement.closest("section").querySelectorAll(".is-thumbs-element");0<=e.length&&e.forEach(e=>{e=e.querySelectorAll(".slide");const i=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")],l=i[n],r=l?.classList.contains("js-clone");
e.forEach(e=>{if(e.classList.remove("js-active"),r){const s=l.dataset.cloneId;var t=i.findIndex(e=>e.dataset.slideId==s);Number(e.dataset.index)===Number(t)&&e.classList.add("js-active")}else Number(e.dataset.index)===Number(n)&&e.classList.add("js-active")})})};setActiveSlideClass=e=>{var t=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),t=t?[...t]:null;null!==e&&(t.map(e=>{e?.classList.remove("js-active")}),0<t.length)&&t[Number(e)].classList.add("js-active")};setListenerArrows=(
)=>{var e=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!e)return null;var t=e?.querySelector(".previous"),e=e?.querySelector(".next");t?.addEventListener("click",()=>this.handlePreviousSlide()),e.addEventListener("click",()=>this.handleNextSlide())};setStylingArrows=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!e)return null;var t=e?.querySelector(".previous"),e=e?.querySelector(".next"),s=this.getCurrentSliderStates();t&&(
0==s?.activeSlide?t.classList.add("js-disabled"):t.classList.remove("js-disabled")),e&&(!0===s?.isSlideTheLastSlide?e.classList.add("js-disabled"):e.classList.remove("js-disabled"))};setScrollPositionWithoutScroll=s=>{var e=this.getCurrentSliderStates()?.allSlideWidths;0<=s&&(e=(e?.map((e,t)=>{if(t<=s-1)return e}).filter(e=>e))?.reduce((e,t)=>e+t,0),this.setActiveSlideClass(s),this.sliderElement.scrollTo({top:0,left:e,behavior:"instant"}))};setScrollPosition=s=>{
var e=this.getCurrentSliderStates()?.allSlideWidths;0<=s&&(e=(e?.map((e,t)=>{if(t<=s-1)return e}).filter(e=>e))?.reduce((e,t)=>e+t,0),this.setActiveSlideClass(s),this.sliderElement.scrollTo({top:0,left:e,behavior:"smooth"}))};getPositionOfSlideById=t=>{return[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")].findIndex(e=>e.dataset.deeplinkTarget==t)};handleClickNewActiveSlide=e=>{var t=e.target.closest(".slide"),e=e.target.closest(".dot");let s=0;t&&(t=t.getAttribute("id"),
s=this.getPositionOfSlideById(t)),e&&(s=e.dataset.index),this.setActiveIndicator(s),this.setActiveThumb(s),this.setScrollPosition(s),this.setStylingArrows(s)};setListenersToTheDots=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__indicator");e&&[...e.querySelectorAll(".dot")]?.map(e=>{e.addEventListener("click",e=>this.handleClickNewActiveSlide(e))})};setListenersToThumbs=()=>{var e;this.sliderConfig.enableThumbs&&(e=this.sliderElement.closest("section").querySelector(
".is-thumbs-element"))&&[...e.querySelectorAll(".slide")]?.map(e=>{const t=e.dataset.index;e.addEventListener("click",()=>{this.setActiveIndicator(t),this.setActiveThumb(t),this.setScrollPosition(t),this.setStylingArrows(t)})})};updateSlides=()=>{this.sliderElement.classList.add("js-updating-slides"),this.setNewDots(),this.setStylingArrows(),this.setClonesOfSlideForInifiteScroll(),this.setListenersToTheDots(),this.sliderElement.classList.remove("js-updating-slides")};callback=this.debounce(e=>{
for(const t of e)"childList"===t.type&&this.updateSlides()},10);setNewDots=this.debounce(()=>{const s=this.coralScrollElement.querySelector(".coral-scroll__indicator");var e;s&&(e=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)")],s.innerHTML="",e.map((e,t)=>{s.insertAdjacentHTML("beforeEnd",this.#createDotElement(t))}))},10);setClonesOfSlideForInifiteScroll=()=>{var e;!0===this.sliderConfig.infinite&&"true"!==this.sliderElement.dataset.clonesActive&&(e=(
e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)"))?[...e]:null,this.sliderElement.dataset.clonesActive="true",e.map((e,t)=>{var s=e.cloneNode(!0);s.classList.add("js-clone"),s.dataset.cloneId=t,this.sliderElement.insertAdjacentElement("beforeend",s),e.dataset.slideId=t}))};handlePreviousSlide=()=>{var e=this.getCurrentSliderStates();let t=e?.activeSlide;0===e?.activeSlide?t=0:--t,this.setActiveIndicator(t),this.setActiveThumb(t),this.setScrollPosition(t),
this.setStylingArrows(t),this.sendEventScrolledToNewSlide(t)};handleNextSlide=()=>{var e=this.getCurrentSliderStates();let t=e?.activeSlide;e?.isSlideTheSecondLastSlide?t=!0===this.sliderConfig.infinite?(e=((e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e)),Number(e)+1):0:t+=1,this.setActiveIndicator(t),this.setActiveThumb(t),this.setScrollPosition(t),this.setStylingArrows(t),
this.sendEventScrolledToNewSlide(t)};setActiveSlide=e=>{this.setActiveIndicator(e),this.setActiveThumb(e),this.setScrollPosition(e),this.setStylingArrows(e),this.sendEventScrolledToNewSlide(e)};setActiveSlideWithoutScroll=e=>{this.setActiveIndicator(e),this.setActiveThumb(e),this.setScrollPositionWithoutScroll(Number(e)),this.setStylingArrows(e),this.sendEventScrolledToNewSlide(e)};handleScroll=()=>{var e,t=this.getCurrentSliderStates();this.setActiveSlideClass(t?.activeSlide),
this.setActiveIndicator(t?.activeSlide),this.setScrollPosition(t?.activeSlide),this.setStylingArrows(t?.activeSlide),t.isSlideTheSecondLastSlide?!0===sliderConfig.infinite&&(e=((e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t.activeSlide]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e))):t.isSlideTheLastSlide&&!0===sliderConfig.infinite&&(e=((e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t.activeSlide
]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e)))};initializeSlider=()=>{const e=this.sliderConfig.startPositionId||0;if(this.setNewDots(),this.setActiveSlideClass(e),this.setListenerArrows(),this.setClonesOfSlideForInifiteScroll(),setTimeout(()=>{this.setListenersToTheDots(),this.setListenersToThumbs(),this.setActiveIndicator(e)},50),this.sliderElement.addEventListener("scroll",this.debounce(()=>{var e=this.getCurrentSliderStates(),t=e?.activeSlide;e!==t&&(
this.setActiveSlideClass(t),this.setActiveIndicator(t),this.setActiveThumb(t),this.setStylingArrows(t))}),0),this.sliderElement.addEventListener("mousedown",()=>{this.showOverlay=!0}),this.sliderElement.addEventListener("mousemove",e=>{this.showOverlay&&(this.grabOverlayElement?.classList.add("js-active"),e=new MouseEvent("mousedown",e),this.grabOverlayElement?.dispatchEvent(e))}),this.sliderElement.addEventListener("mouseup",()=>{var e=new MouseEvent("mouseup");
this.grabOverlayElement?.classList.remove("js-active"),this.grabOverlayElement?.dispatchEvent(e),this.showOverlay=!1}),this.grabOverlayElement){this.grabOverlayElement.addEventListener("mousedown",e=>{var t=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")];this.isDown=!0,this.sliderElement.classList.add("js-active"),this.startX=e.pageX-this.sliderElement.offsetLeft,t.map(e=>{e.ondragstart=function(){return!1}})});const t=()=>{this.isDown=!1,
this.grabOverlayElement.classList.remove("js-active"),this.showOverlay=!1,setTimeout(()=>{this.sliderElement.classList.remove("js-active")},1e3)};this.grabOverlayElement.addEventListener("mouseup",e=>t()),this.grabOverlayElement.addEventListener("mousemove",e=>{var t;this.isDown&&(e.preventDefault(),t=this.getCurrentSliderStates(),(e=e.pageX-this.sliderElement.offsetLeft-this.startX)>=-this.sliderConfig.grabVelocity&&e<=0&&this.setScrollPosition(t.activeSlide+1),e>=this.sliderConfig.grabVelocity
)&&0<=e&&this.setScrollPosition(t.activeSlide-1)})}}}export default CoralScrollCore;export{CoralScrollCore};