class CoralScrollCore{constructor(e){this.coralScrollElement=e,this.sliderElement=e.querySelector(".coral-scroll__slider"),this.grabOverlayElement=e.querySelector(".coral-scroll__grab-overlay"),this.sliderConfig=this.createSliderConfig(),this.slideScrollLeft=this.sliderElement.scrollLeft,this.showOverlay=!1,this.isDown=!1,this.startX,this.isTouchDown=!1,this.coralScrollId=Date.now(),this.shadowActiveSlidePosition=0,this.handleInterval,this.initializeSlider(),this.oberserverConfig={attributes:!1,
childList:!0,subtree:!1}}createSliderConfig=()=>{var e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")?this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")[0]:null;return{devMode:!!this.coralScrollElement.dataset.devMode&&"true"===this.coralScrollElement.dataset.devMode,grabVelocity:this.coralScrollElement.dataset.grabVelocity||100,autoScrollDuration:this.coralScrollElement.dataset.autoScroll||!1,enableThumbs:this.coralScrollElement.dataset.thumbs||!1,
isThumbsSlider:!!this.coralScrollElement.dataset.isThumbsSlider,infinite:"true"===this.coralScrollElement.dataset.infiniteScroll,snapAlignStyle:e?getComputedStyle(e)["scroll-snap-align"]:null,startPositionId:this.coralScrollElement.dataset.startPositionId,slideGrouping:this.coralScrollElement.dataset.group||0,sliderClass:this.coralScrollElement.classList,slidesPerGroup:this.coralScrollElement.dataset.slidesPerGroup||1,verticalOrHorizontal:"y mandatory"===getComputedStyle(this.sliderElement)[
"scroll-snap-type"]?"vertical":"horizontal"}};debounce=(s,t=50)=>{let l;return(...e)=>{clearTimeout(l),l=setTimeout(()=>{s.apply(this,e)},t)}};createRequestToSlideEvent=(e,s)=>{s=new CustomEvent("request-to-slide",{detail:{slideId:s,targetSliderClass:e,sendFromSliderElement:this.coralScrollElement}});document.dispatchEvent(s)};sendScrolledToSlideEvent=e=>{e=new CustomEvent("scrolled-to-slide",{detail:{activeSlide:e,sendFromSliderElement:this.coralScrollElement}});document.dispatchEvent(e)};
returnNewSlideId=()=>parseInt((9*Math.random()+1)*Math.pow(10,8),10);handleInitialSlideId=()=>{this.sliderElement.querySelectorAll(".slide:not(.js-hidden)").forEach(e=>{var s;e.dataset.slideId||(s=this.returnNewSlideId(),e.dataset.slideId=s)})};handleNextSlide=()=>{var e,s=this.sliderElement.querySelector(".slide.js-next-slide:not(.js-hidden)");s&&(s=s?.dataset.slideId,this.coralScrollElement.dataset.thumbsParentClass,e=this.coralScrollElement.classList,this.createRequestToSlideEvent(e,s))};
handleNextGrabSlide=this.debounce(()=>{this.handleNextSlide()},100);handlePreviousSlide=()=>{var e,s=this.sliderElement.querySelector(".slide.js-previous-slide:not(.js-hidden)");s&&(s=s?.dataset.slideId,this.coralScrollElement.dataset.thumbsParentClass,e=this.coralScrollElement.classList,this.createRequestToSlideEvent(e,s))};handlePreviousGrabSlide=this.debounce(()=>{this.handlePreviousSlide()},100);setStartPositionSlideActive=e=>{var s=this.sliderElement.querySelectorAll(
".slide:not(.js-hidden)"),s=(s?[...s]:null)[e].dataset.slideId;this.coralScrollElement.classList;this.scrollToSlideId(s)};setListenerArrows=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!e)return null;var s=e?.querySelector(".previous"),e=e?.querySelector(".next");s?.addEventListener("click",()=>this.handlePreviousSlide()),e.addEventListener("click",()=>this.handleNextSlide())};setNextAndPreviousSlideClass=e=>{var s=this.sliderElement.querySelectorAll(
".slide:not(.js-hidden)"),s=s?[...s]:null,t=this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)"),t=t?[...t]:null,l=t[0],t=t[t.length-1];s.forEach(e=>{e.classList.remove("js-previous-slide"),e.classList.remove("js-next-slide")});let i=e?.previousElementSibling,r=e?.nextElementSibling;if(t===e){if(console.log("last slide"),1<this.sliderConfig.slidesPerGroup)for(let e=1;e<this.sliderConfig.slidesPerGroup;e++)i=i?.previousElementSibling||i;i&&i?.classList.add(
"js-previous-slide"),this.sliderConfig.infinite&&l?.classList.add("js-next-slide")}else if(l===e){if(console.log("first slide"),1<this.sliderConfig.slidesPerGroup)for(let e=1;e<this.sliderConfig.slidesPerGroup;e++)r=r?.nextElementSibling||r;r&&r?.classList.add("js-next-slide"),this.sliderConfig.infinite&&t?.classList.add("js-previous-slide")}else{if(console.log("genreral slide case"),1<this.sliderConfig.slidesPerGroup)for(let e=1;e<this.sliderConfig.slidesPerGroup;e++
)i=i?.previousElementSibling||i,r=r?.nextElementSibling||r;i&&i?.classList.add("js-previous-slide"),r&&r?.classList.add("js-next-slide")}};groupArr=(t,l)=>{var i=[];for(let e=0,s=0;e<t.length;e++)e>=l&&e%l==0&&s++,i[s]=i[s]||[],i[s].push(t[e]);return i};setClonesOfSlideForInifiteScroll=()=>{var e,s;!0===this.sliderConfig.infinite&&"true"!==this.sliderElement.dataset.clonesActive&&(s=(s=this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)"))?[...s]:null,
this.sliderElement.dataset.clonesActive="true",e=(s=this.groupArr(s,this.sliderConfig.slidesPerGroup))[0],(s=s[s.length-1])&&s.map(e=>{var s=e.cloneNode(!0);s.classList.remove("js-active"),s.classList.add("js-clone"),s.dataset.slideId=this.returnNewSlideId(),s.dataset.cloneId=e.dataset.slideId,this.sliderElement.insertAdjacentElement("afterbegin",s)}),e)&&e.map(e=>{var s=e.cloneNode(!0);s.classList.remove("js-active"),s.classList.add("js-clone"),s.dataset.slideId=this.returnNewSlideId(),
s.dataset.cloneId=e.dataset.slideId,this.sliderElement.insertAdjacentElement("beforeend",s)})};scrollToSlideId=e=>{var s,e=this.sliderElement.querySelector(`[data-slide-id="${e}"]:not(.js-hidden)`);"vertical"===this.sliderConfig.verticalOrHorizontal?(s=e?.offsetTop,this.sliderElement.scrollTo({top:s,left:0,behavior:"smooth"})):(s=e?.offsetLeft,this.sliderElement.scrollTo({top:0,left:s,behavior:"smooth"}))};setActiveSlideClass=e=>{var s=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"
);(s?[...s]:null).map(e=>{e?.classList.remove("js-active")}),e?.classList.add("js-active")};setStylingArrows=e=>{var s=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!s)return null;var t=s?.querySelector(".previous"),s=s?.querySelector(".next"),l=this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)"),l=l?[...l]:null,i=l[0],l=l[l.length-1];t&&(!0!==this.sliderConfig.infinite&&i===e?t.classList.add("js-disabled"):t.classList.remove("js-disabled")),s&&(
!0!==this.sliderConfig.infinite&&l===e?s.classList.add("js-disabled"):s.classList.remove("js-disabled"))};setActiveThumbs=e=>{var s=this.sliderConfig.enableThumbs;document.querySelectorAll(".coral-scroll."+s)?.forEach(e=>{!1===this.sliderConfig.isThumbsSlider&&e&&e.querySelectorAll(".slide").forEach(e=>{e.classList.remove("js-active");e=e.dataset.slideId,e=new CustomEvent("request-to-slide",{detail:{slideId:e,targetSliderClass:this.sliderConfig.enableThumbs.classList,
sendFromSliderElement:this.coralScrollElement}});document.dispatchEvent(e)})})};handleSettingNextAndPreviousSlide=e=>{e=this.sliderElement.querySelector(`[data-slide-id="${e}"]:not(.js-hidden)`);console.log(e),this.setNextAndPreviousSlideClass(e)};handleSettingNextAndPreviousSlideBySlideIndex=e=>{var s=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),s=(s?[...s]:null)[e];this.setNextAndPreviousSlideClass(s)};setGeneralSliderListeners=()=>{document.addEventListener("request-to-slide"
,e=>{var e=e.detail,s=e.targetSliderClass,e=e.slideId;s===this.sliderConfig.sliderClass&&(console.log("request to slide",e),s=this.sliderElement.querySelector(`[data-slide-id="${e}"]:not(.js-hidden)`),this.setNextAndPreviousSlideClass(s),this.setActiveSlideClass(s),this.setStylingArrows(s),this.scrollToSlideId(e),this.sendScrolledToSlideEvent(e))}),document.addEventListener("scrolled-to-slide",e=>{var e=e.detail,s=e.activeSlide,e=e.sendFromSliderElement,s=this.sliderElement.querySelector(
`[data-slide-id="${s}"]:not(.js-hidden)`);e==this.coralScrollElement&&s.classList.contains("js-clone")&&this.handleNextSlide()})};setListenersGrab=()=>{if(this.sliderElement.addEventListener("mousedown",()=>{this.showOverlay=!0}),this.sliderElement.addEventListener("mousemove",e=>{this.showOverlay&&(this.grabOverlayElement?.classList.add("js-active"),e=new MouseEvent("mousedown",e),this.grabOverlayElement?.dispatchEvent(e))}),this.sliderElement.addEventListener("mouseup",()=>{
var e=new MouseEvent("mouseup");this.grabOverlayElement?.classList.remove("js-active"),this.grabOverlayElement?.dispatchEvent(e),this.showOverlay=!1}),this.grabOverlayElement){this.grabOverlayElement.addEventListener("mousedown",e=>{var s=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")];this.isDown=!0,this.sliderElement.classList.add("js-active"),this.startX=e.pageX-this.sliderElement.offsetLeft,s.map(e=>{e.ondragstart=function(){return!1}})});const s=()=>{this.isDown=!1,
this.grabOverlayElement.classList.remove("js-active"),this.showOverlay=!1,setTimeout(()=>{this.sliderElement.classList.remove("js-active")},1e3)};this.grabOverlayElement.addEventListener("mouseup",e=>s()),this.grabOverlayElement.addEventListener("mousemove",e=>{this.isDown&&(e.preventDefault(),(e=e.pageX-this.sliderElement.offsetLeft-this.startX)>=-this.sliderConfig.grabVelocity&&e<=0&&this.handleNextGrabSlide(),e>=this.sliderConfig.grabVelocity)&&0<=e&&this.handlePreviousGrabSlide()})}};
initializeSlider=()=>{this.handleInitialSlideId();var e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),e=e?[...e]:null;let s=0;s=this.sliderConfig.startPositionId||(l=this.sliderElement.querySelector(".slide:not(.js-hidden):not(.js-clone)"),e.indexOf(l));const t=e[s];var l=t?.dataset.slideId;this.coralScrollElement.dataset.coralScrollId=this.coralScrollId,this.setStartPositionSlideActive(s),this.sliderConfig.isThumbsSlider||this.setActiveSlideClass(t),this.setStylingArrows(t),
this.setListenerArrows(),this.setClonesOfSlideForInifiteScroll(),this.handleSettingNextAndPreviousSlide(l),this.setGeneralSliderListeners(),this.setListenersGrab(),setTimeout(()=>{this.setActiveThumbs(t)},50)}}export default CoralScrollCore;export{CoralScrollCore};