class CoralScrollCore{constructor(e){this.coralScrollElement=e,this.sliderElement=e.querySelector(".coral-scroll__slider"),this.grabOverlayElement=e.querySelector(".coral-scroll__grab-overlay"),this.sliderConfig=this.createSliderConfig(),this.slideScrollLeft=this.sliderElement.scrollLeft,this.showOverlay=!1,this.isDown=!1,this.startX,this.isTouchDown=!1,this.shadowActiveSlidePosition=0,this.initializeSlider(),this.oberserverConfig={attributes:!1,childList:!0,subtree:!1},new MutationObserver(
this.callback).observe(this.coralScrollElement,this.oberserverConfig)}#createDotElement=e=>`<button type="button" class="dot" data-index="${e}" aria-label="Select slide ${e}" name="Select slide ${e}"></button>`;sendEventScrolledToNewSlide=e=>{e=new CustomEvent("scrolled-to-slide",{detail:{activeSlide:e,sendFromSliderElement:this.coralScrollElement}});document.dispatchEvent(e)};sendEventRequestToScrollToNewSlide=(e,t)=>{e=new CustomEvent("request-to-slide",{detail:{activeSlide:e,
targetSliderClass:t,sendFromSliderElement:this.coralScrollElement}});document.dispatchEvent(e)};debounce=(t,i=50)=>{let s;return(...e)=>{clearTimeout(s),s=setTimeout(()=>{t.apply(this,e)},i)}};createSliderConfig=()=>{var e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")?this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")[0]:null;return{devMode:!!this.coralScrollElement.dataset.devMode&&"true"===this.coralScrollElement.dataset.devMode,
grabVelocity:this.coralScrollElement.dataset.grabVelocity||100,autoScrollDuration:this.coralScrollElement.dataset.autoScroll||!1,enableThumbs:this.coralScrollElement.dataset.thumbs||!1,isThumbsSlider:!!this.coralScrollElement.dataset.isThumbsSlider,infinite:"true"===this.coralScrollElement.dataset.infiniteScroll,snapAlignStyle:e?getComputedStyle(e)["scroll-snap-align"]:null,startPositionId:this.coralScrollElement.dataset.startPositionId}};getCurrentSliderStates=()=>{if(!this.sliderElement
)return null;var t=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),t=t?[...t]:null,i=getComputedStyle(this.sliderElement).paddingLeft.replace("px",""),s=getComputedStyle(this.sliderElement).gap;const l=s?.split(" ")?s?.split(" ")[0].replace("px",""):s?.replace("px","");var r=this.sliderElement.getBoundingClientRect().width;const o=t.length,n=Number(this.sliderElement.getBoundingClientRect().left)+Number(i);s=t.map(e=>{var t=e.getBoundingClientRect().x,i=e.getBoundingClientRect(
).width;this.sliderElement.getBoundingClientRect().width,getComputedStyle(this.sliderElement).paddingLeft.replace("px",""),getComputedStyle(this.sliderElement).paddingRight.replace("px","");switch(this.sliderConfig.snapAlignStyle){case"start":return Number(t)-Number(n);case"center":return Number(t)-Number(n)+Number(i/2);default:return t}}),i=t.map(e=>{var t=e.getBoundingClientRect().x,e=e.getBoundingClientRect().width;return Number(t)+Number(e)}),t=t.map((e,t)=>{e=e.getBoundingClientRect().width
return t===o?Number(e):Number(e)+Number(l.match(/^[0-9]+$/)?l:0)});if(0<s.length){const h=s?.reduce((e,t)=>Math.abs(+t)<Math.abs(+e)?t:e);var d=s?.findIndex(e=>e===h),a=getComputedStyle(this.sliderElement).paddingRight.replace("px",""),c=Math.ceil(i[o-1]),i=d===Number(o)-2;let e=null;switch(this.sliderConfig.snapAlignStyle){case"start":e=Number(c)+Number(a)<=Number(r)+10&&Number(c)+Number(a)>=Number(r)-10;break;case"center":e=c-a==r/2;break;default:e=c===r}t={allSlideWidths:t,
currentSlidePositions:s,activeSlide:d,isSlideTheSecondLastSlide:i,isSlideTheLastSlide:e,sliderElement:this.coralScrollElement};return this.sliderConfig.devMode&&console.log(t),t}return 0};setActiveIndicator=s=>{var e=this.coralScrollElement.querySelector(".coral-scroll__indicator");if(e){e=e.querySelectorAll(".dot");const l=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")],r=l[s],o=r?.classList.contains("js-clone");e.forEach(e=>{if(e.classList.remove("js-active"),o){
const i=r.dataset.cloneId;var t=l.findIndex(e=>e.dataset.slideId==i);Number(e.dataset.index)===Number(t)&&e.classList.add("js-active")}else Number(e.dataset.index)===Number(s)&&e.classList.add("js-active")})}};setActiveThumb=n=>{var e=this.sliderConfig.enableThumbs;document.querySelectorAll("."+e).forEach(e=>{if(!1===this.sliderConfig.isThumbsSlider&&e){e=e.querySelectorAll(".slide");const s=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")],l=s[n],r=l.dataset.imageId,
o=l?.classList.contains("js-clone");e.forEach(e=>{if(e.classList.remove("js-active"),o){const i=l.dataset.cloneId;var t=s.findIndex(e=>e.dataset.slideId==i);Number(e.dataset.index)===Number(t)&&(e.classList.add("js-active"),this.sendEventRequestToScrollToNewSlide(n,this.sliderConfig.enableThumbs))}else e.dataset.imageId===r&&(e.classList.add("js-active"),this.sendEventRequestToScrollToNewSlide(n,this.sliderConfig.enableThumbs))})}})};setActiveSlideClass=e=>{
var t=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),t=t?[...t]:null;null!==e&&(t.map(e=>{e?.classList.remove("js-active")}),0<t.length)&&t[Number(e)]?.classList.add("js-active")};setListenerArrows=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!e)return null;var t=e?.querySelector(".previous"),e=e?.querySelector(".next");t?.addEventListener("click",()=>this.handlePreviousSlide()),e.addEventListener("click",()=>this.handleNextSlide())};
setStylingArrows=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__arrows");if(!e)return null;var t=e?.querySelector(".previous"),e=e?.querySelector(".next"),i=this.getCurrentSliderStates();t&&(0==i?.activeSlide?t.classList.add("js-disabled"):t.classList.remove("js-disabled")),e&&(!0===i?.isSlideTheLastSlide?e.classList.add("js-disabled"):e.classList.remove("js-disabled"))};setScrollPositionWithoutScroll=i=>{var e=this.getCurrentSliderStates()?.allSlideWidths;0<=i&&(e=(e?.map((e,t
)=>{if(t<=i-1)return e}).filter(e=>e))?.reduce((e,t)=>e+t,0),this.setActiveSlideClass(i),this.sliderElement.scrollTo({top:0,left:e,behavior:"instant"}))};setScrollPosition=i=>{var e=this.getCurrentSliderStates()?.allSlideWidths;0<=i&&(e=(e?.map((e,t)=>{if(t<=i-1)return e}).filter(e=>e))?.reduce((e,t)=>e+t,0),this.setActiveSlideClass(i),this.sliderElement.scrollTo({top:0,left:e,behavior:"smooth"}))};setScrollPositionNotActive=i=>{var e=this.getCurrentSliderStates()?.allSlideWidths;0<=i&&(e=(
e?.map((e,t)=>{if(t<=i-1)return e}).filter(e=>e))?.reduce((e,t)=>e+t,0),this.sliderElement.scrollTo({top:0,left:e,behavior:"smooth"}))};getPositionOfSlideById=t=>{return[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")].findIndex(e=>e.dataset.deeplinkTarget==t)};handleClickNewActiveSlide=e=>{var t=e.target.closest(".slide"),e=e.target.closest(".dot");let i=0;t&&(t=t.getAttribute("id"),i=this.getPositionOfSlideById(t)),e&&(i=e.dataset.index),this.setActiveIndicator(i),
this.setActiveThumb(i),this.setScrollPosition(i),this.setStylingArrows(i)};setListenersToTheDots=()=>{var e=this.coralScrollElement.querySelector(".coral-scroll__indicator");e&&[...e.querySelectorAll(".dot")]?.map(e=>{e.addEventListener("click",e=>this.handleClickNewActiveSlide(e))})};setListenersToThumbs=()=>{if(this.sliderConfig.isThumbsSlider){var e=[...this.sliderElement.querySelectorAll(".slide")];const s=this.coralScrollElement.dataset.thumbsParentClass;e?.map((e,t)=>{const i=t;
e.addEventListener("click",()=>{this.sendEventRequestToScrollToNewSlide(i,s)})})}};updateSlides=()=>{this.sliderElement.classList.add("js-updating-slides"),this.setNewDots(),this.setStylingArrows(),this.setClonesOfSlideForInifiteScroll(),this.setListenersToTheDots(),this.sliderElement.classList.remove("js-updating-slides")};callback=this.debounce(e=>{for(const t of e)"childList"===t.type&&this.updateSlides()},10);setNewDots=this.debounce(()=>{const i=this.coralScrollElement.querySelector(
".coral-scroll__indicator");var e;i&&(e=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)")],i.innerHTML="",e.map((e,t)=>{i.insertAdjacentHTML("beforeEnd",this.#createDotElement(t))}))},10);setClonesOfSlideForInifiteScroll=()=>{var e;!0===this.sliderConfig.infinite&&"true"!==this.sliderElement.dataset.clonesActive&&(e=(e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden):not(.js-clone)"))?[...e]:null,this.sliderElement.dataset.clonesActive="true",e.map((e,t
)=>{var i=e.cloneNode(!0);i.classList.add("js-clone"),i.dataset.cloneId=t,this.sliderElement.insertAdjacentElement("beforeend",i),e.dataset.slideId=t}))};handlePreviousSlide=()=>{var e=this.getCurrentSliderStates();let t=e?.activeSlide;0===e?.activeSlide?t=0:--t,this.sliderConfig.isThumbsSlider?(0<t?--this.shadowActiveSlidePosition:0===t&&(this.shadowActiveSlidePosition=0),this.setScrollPositionNotActive(this.shadowActiveSlidePosition)):(this.shadowActiveSlidePosition=t,this.setActiveIndicator(t
),this.setActiveThumb(t),this.setScrollPosition(t),this.setStylingArrows(t),this.sendEventScrolledToNewSlide(t))};handleNextSlide=()=>{var e=this.getCurrentSliderStates();let t=e?.activeSlide;e?.isSlideTheSecondLastSlide?t=!0===this.sliderConfig.infinite?(e=((e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e)),Number(e)+1):0:t+=1,this.sliderConfig.isThumbsSlider?(e=((
e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null).length,t<=e&&(this.shadowActiveSlidePosition+=1),this.setScrollPositionNotActive(this.shadowActiveSlidePosition)):(this.shadowActiveSlidePosition=t,this.setActiveIndicator(t),this.setActiveThumb(t),this.setScrollPosition(t),this.setStylingArrows(t),this.sendEventScrolledToNewSlide(t))};handleNextGrabSlide=this.debounce(()=>{var e,t=this.getCurrentSliderStates();this.sliderConfig.isThumbsSlider?(e=((
e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null).length,this.shadowActiveSlidePosition+1<=e&&(this.shadowActiveSlidePosition+=1),this.setScrollPositionNotActive(this.shadowActiveSlidePosition)):this.setScrollPosition(t.activeSlide+1)},100);handlePreviousGrabSlide=this.debounce(()=>{var e=this.getCurrentSliderStates();this.sliderConfig.isThumbsSlider?(0<this.shadowActiveSlidePosition-1?--this.shadowActiveSlidePosition:this.shadowActiveSlidePosition-1==0&&(
this.shadowActiveSlidePosition=0),this.setScrollPositionNotActive(this.shadowActiveSlidePosition)):this.setScrollPosition(e.activeSlide-1)},100);setActiveSlide=e=>{this.setActiveIndicator(e),this.setActiveThumb(e),this.setScrollPosition(e),this.setStylingArrows(e),this.sendEventScrolledToNewSlide(e)};setActiveSlideWithoutScroll=e=>{this.setActiveIndicator(e),this.setActiveThumb(e),this.setScrollPositionWithoutScroll(Number(e)),this.setStylingArrows(e),this.sendEventScrolledToNewSlide(e)};
handleScroll=()=>{var e,t=this.getCurrentSliderStates();this.setActiveSlideClass(t?.activeSlide),this.setActiveIndicator(t?.activeSlide),this.setScrollPosition(t?.activeSlide),this.setStylingArrows(t?.activeSlide),t.isSlideTheSecondLastSlide?!0===sliderConfig.infinite&&(e=((e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t.activeSlide]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e))):t.isSlideTheLastSlide&&!0===sliderConfig.infinite&&(e=((
e=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"))?[...e]:null)[t.activeSlide]?.dataset.cloneId,this.setScrollPositionWithoutScroll(Number(e)))};initializeSlider=()=>{const e=this.sliderConfig.startPositionId||0;if(this.setNewDots(),this.setActiveSlideClass(e),this.setListenerArrows(),this.setClonesOfSlideForInifiteScroll(),setTimeout(()=>{this.setListenersToTheDots(),this.setListenersToThumbs(),this.setActiveIndicator(e)},50),document.addEventListener("request-to-slide",e=>{
var e=e.detail,t=e.activeSlide,e=e.targetSliderClass,i=this.sliderElement.querySelectorAll(".slide:not(.js-hidden)"),i=(i?[...i]:null).length;0<=t&&t<=i&&(this.shadowActiveSlidePosition=t),this.coralScrollElement.classList.contains(e)&&this.setActiveSlide(t)}),this.sliderConfig.isThumbsSlider||this.sliderElement.addEventListener("scroll",this.debounce(()=>{var e=this.getCurrentSliderStates(),t=e?.activeSlide;e!==t&&(this.setActiveSlideClass(t),this.setActiveIndicator(t),this.setActiveThumb(t),
this.setStylingArrows(t))}),0),this.sliderConfig.autoScrollDuration){const i=this.debounce(()=>{!1===this.isTouchDown&&this.handleNextSlide()},100);let t=setInterval(i,this.sliderConfig.autoScrollDuration);this.sliderElement.addEventListener("touchstart",()=>{this.isTouchDown=!0,clearInterval(t),this.coralScrollElement.style.setProperty("--animation-state","paused")},!0,{passive:!0}),this.sliderElement.addEventListener("touchend",()=>{this.isTouchDown=!1,t=setInterval(i,
this.sliderConfig.autoScrollDuration),this.coralScrollElement.style.setProperty("--animation-state","running")},!0,{passive:!0}),document.addEventListener("scrolled-to-slide",e=>{e=e.detail.sendFromSliderElement;console.log("request sen"),e===this.coralScrollElement&&(clearInterval(t),this.coralScrollElement.style.setProperty("--animation-state","paused"))},!0,{passive:!0}),this.sliderElement.addEventListener("mouseenter",()=>{this.isTouchDown=!0,clearInterval(t),
this.coralScrollElement.style.setProperty("--animation-state","paused")},!0,{passive:!0}),this.sliderElement.addEventListener("mouseleave",this.debounce(()=>{this.isTouchDown=!1,t=setInterval(i,this.sliderConfig.autoScrollDuration),this.coralScrollElement.style.setProperty("--animation-state","running")},100),!0,{passive:!0})}if(this.sliderElement.addEventListener("mousedown",()=>{this.showOverlay=!0}),this.sliderElement.addEventListener("mousemove",e=>{this.showOverlay&&(
this.grabOverlayElement?.classList.add("js-active"),e=new MouseEvent("mousedown",e),this.grabOverlayElement?.dispatchEvent(e))}),this.sliderElement.addEventListener("mouseup",()=>{var e=new MouseEvent("mouseup");this.grabOverlayElement?.classList.remove("js-active"),this.grabOverlayElement?.dispatchEvent(e),this.showOverlay=!1}),this.grabOverlayElement){this.grabOverlayElement.addEventListener("mousedown",e=>{var t=[...this.sliderElement.querySelectorAll(".slide:not(.js-hidden)")];this.isDown=!0
,this.sliderElement.classList.add("js-active"),this.startX=e.pageX-this.sliderElement.offsetLeft,t.map(e=>{e.ondragstart=function(){return!1}})});const t=()=>{this.isDown=!1,this.grabOverlayElement.classList.remove("js-active"),this.showOverlay=!1,setTimeout(()=>{this.sliderElement.classList.remove("js-active")},1e3)};this.grabOverlayElement.addEventListener("mouseup",e=>t()),this.grabOverlayElement.addEventListener("mousemove",e=>{this.isDown&&(e.preventDefault(),(
e=e.pageX-this.sliderElement.offsetLeft-this.startX)>=-this.sliderConfig.grabVelocity&&e<=0&&this.handleNextGrabSlide(),e>=this.sliderConfig.grabVelocity)&&0<=e&&this.handlePreviousGrabSlide()})}}}export default CoralScrollCore;export{CoralScrollCore};